### ISSUE TITLE
Add sharing callback

### ISSUE THREAD

**Issue by olokobayusuf** [olokobayusuf/NatShare-API#10]
The callback should ideally provide information as to whether the user actually shared, or whether they cancelled.

**Comment by ValentinChareyre** [comment]
Any news about this feature?

I saw the PR [here](https://github.com/olokobayusuf/NatShare-API/pull/14) but it seems it won't be merged.

**Comment by olokobayusuf** [comment]
Hi there Valentin. The reason I haven't merged #14 is because we can't add the same feature on Android. We try to offer the exact same feature set on iOS and Android at the very least, and this feature will break that. I guess a feature like this is worth it. I'll merge #14 today or tomorrow.

**Comment by olokobayusuf** [comment]
Hey @ValentinChareyre, sorry I got to this super late. Check out #35 (and consider leaving a review, especially with your thoughts on the share callback dilemma).

**Comment by ValentinChareyre** [comment]
@olokobayusuf : Thanks a lot for the work you and @sroske did on this feature. I believe the "parameter-less" callback is better than nothing and is a great improvement for your very nice plugin! I hope Android will fix the issue with their API on this problem. I will give a try and give you a feedback ASAP.

**Comment by mikkoh** [comment]
Might be good to add this to `SaveToCameraRoll` also:

If you do:
```
NatShare.SaveToCameraRoll(path);
System.IO.File.Delete(path);
```
The file will never be saved to the Camera Roll.

**Comment by olokobayusuf** [comment]
@mikkoh this is pretty fair, but providing a callback for saving to the camera roll seems a bit overkill since the only use case I've seen so far is just deleting the file from app storage. Instead, it'll be more natural for the client to provide a `copy` argument to `SaveToCameraRoll`. Let's move this conversation to #38 .
