### ISSUE TITLE
Save to album in camera roll

### ISSUE THREAD

**Issue by TobiasWehrum** [olokobayusuf/NatShare-API#15]
I'm describing the feature for Android; I'm not sure if it can work similarly under iOS.

Currently the pictures saved to camera roll are always found in the camera roll folder "Pictures" because they are saved directly to the ENVIRONMENT.DIRECTORY_PICTURES folder.

It would be great to be able to add the name of a subfolder as a second argument to SaveToCameraRoll().

Being able to name the pictures would also be nice.

**Comment by olokobayusuf** [comment]
I've changed the name of this issue to be a bit clearer. This is a good feature request, so I'll look into adding it.

**Comment by yosun** [comment]
Is this on a roadmap?

**Comment by olokobayusuf** [comment]
Completed in af61032a7df8cf68e4349c88add47edef5a7fac0
