### ISSUE TITLE
Sharing on twitter not working

### ISSUE THREAD

**Issue by andremarques-gamedev** [olokobayusuf/NatShare-API#16]
The sharing on any other platform like facebook, discord, slack, facebook messeger and etc. Its working fine but on twitter only shows up the text and the image isn't shared.

I tested this with an android phone

**Comment by olokobayusuf** [comment]
I did some digging and apparently, [it is a bug in the Twitter app itself](https://twittercommunity.com/t/it-is-impossible-to-share-text-and-image-both-on-twitter-android-share-intent/5633).
