### ISSUE TITLE
Twitter sharing image not working

### ISSUE THREAD

**Issue by andremarques-gamedev** [olokobayusuf/NatShare-API#19]
A simple image sharing is not working on twitter enven if i passa empty string on message it doesnt share the image. I talked to someone on twitter they said that the android doesnt like very much to pass a uri file:// and the alternative would be passinga uri that its not file:// , they also advised a workaround would be some thing like this StrictMode.setVmPolicy(StrictMode.VmPolicy.LAX);

Could you take a look on this ? or tell how ae you doing it ?

**Comment by andremarques-gamedev** [comment]
Found that this was related to twitter not having permissions to access images.

**Comment by olokobayusuf** [comment]
I've only just been able to respond to this. Good find.
