### ISSUE TITLE
Sharing video on skype 

### ISSUE THREAD

**Issue by AbhayaAgrawal1** [olokobayusuf/NatShare-API#32]
While sharing video on Skype over Andorid platform it shares video not text
and while sharing on Skype over iOS platform it shares text not video

**Comment by olokobayusuf** [comment]
This isn't up to NatShare. The receiving app (in this case, Skype) decides what parts of the sharing payload it accepts. For instance, Instagram on iOS will reject a sharing payload if the payload contains text.

**Comment by AbhayaAgrawal1** [comment]
If you have exceptions list. Kindly provide.

**Comment by olokobayusuf** [comment]
I don't, sorry.
