### ISSUE TITLE
SaveToCameraRoll

### ISSUE THREAD

**Issue by shinbuck** [olokobayusuf/NatShare-API#33]
When using 'NatShare.SaveToCameraRoll(Texture2D texture)', there is a significant delay before image is saved to your device on the Android. Saving video to file is fine. Additional plugin that is being used is ARCore. This delay doesn't occur on iOS using ARKit.

**Comment by shinbuck** [comment]
It is 60 kb

**Comment by olokobayusuf** [comment]
Sorry, I meant big as in resolution.

**Comment by shinbuck** [comment]
1080 x 1731,
I'm saving the image to a Texture2D with the following code snippet below:
`            m_screenTexture = new Texture2D(Screen.width, Screen.height, TextureFormat.RGB24, false);
            m_screenTexture.ReadPixels(new Rect(0,0,Screen.width,Screen.height), 0, 0);
            m_screenTexture.LoadImage(m_screenTexture.EncodeToPNG());`

I also have Natcorder, is there a recommended way to capture a single screen capture?

**Comment by olokobayusuf** [comment]
You should use the `ScreenCapture.CaptureScreenshotAsTexture` function, then pass the generated texture to `NatShare.ShareImage`. Your code is expected to be slow, since you are reading pixels, encoding to a PNG, then loading it back into the texture. I am closing this issue.
