### ISSUE TITLE
Add text sharing with video

### ISSUE THREAD

**Issue by antoniotonev** [olokobayusuf/NatShare-API#4]
Hello,

Please add sharing a text feature with video sharing in next version. 😊
Thank you.

**Comment by olokobayusuf** [comment]
I will look into this and open a pull request if it is feasible.

**Comment by antoniotonev** [comment]
👍🏻👍🏻👍🏻👍🏻👌👌👌👌😎😎😎😎😎

**Comment by olokobayusuf** [comment]
See #5

**Comment by olokobayusuf** [comment]
This feature has been implemented: c8ee117a3a22b6538412c9a76d39d7b6a054e494

**Comment by FomTarro** [comment]
Feature does not appear to work on Android (tested on Android 7.0)

**Comment by olokobayusuf** [comment]
I've reopened the issue. I'll look into this.

**Comment by FomTarro** [comment]
Based on a little investigation about current Android standards, I think you need to use a "ContentProvider" class to deliver media + text via the sharing context. I am not sure if that helps.

**Comment by olokobayusuf** [comment]
Apparently some apps ignore the text passed to `Intent.createChooser`, so you have to add the text in the payload. 756ebe5efe1123a3384aa27dcc975bc5a1997c3c fixes this. I've updated the release with this fix, and I'm closing the issue.
