### ISSUE TITLE
 NatShare.GetThumbnail for gif files

### ISSUE THREAD

**Issue by yosun** [olokobayusuf/NatShare-API#42]
For completeness of animated media returns: NatShare.GetThumbnail should return a thumbnail for gif files as well.

**Comment by olokobayusuf** [comment]
GIF files are images whereas `GetThumbnail` is meant for videos. The semantics for this function doesn't carry over to GIF's. Also, the native functions for actually getting thumbnails don't support GIF's.

**Comment by yosun** [comment]
What do you suggest for loading or showing thumbs of gif's created using Nat*?

**Comment by olokobayusuf** [comment]
[Here](https://assetstore.unity.com/search?k=gif&order_by=relevance&q=gif&rows=42) are a few options. Since you only need playback, it looks like "GIF Play Plugin" and "Animated GIF Player" are good options.
