### ISSUE TITLE
Video Share on Instagram Story

### ISSUE THREAD

**Issue by Russel1** [olokobayusuf/NatShare-API#43]
Hi,

I would like to share a video directly to the Instagram story without having to choose between "Feed" and "Story". Is this somehow possible with the NatShare-API?

Here you can find documentation about the Instagram Story Share:
https://developers.facebook.com/docs/instagram/sharing-to-stories/

Thanks for your help.

**Comment by olokobayusuf** [comment]
NatShare doesn't deal with sharing at a deeper level than the OS sharesheet. You should instead clone the sources and modify it to do this.
