### ISSUE TITLE
Can't I send an message anymore when sharing a Image?

### ISSUE THREAD

**Issue by andremarques-gamedev** [olokobayusuf/NatShare-API#51]
I have used a previous version of this plugin where you could Share an Image and insert a message also, is this feature no longer available?

**Comment by olokobayusuf** [comment]
We removed it because most apps will either reject the share payload, or would only extract parts of it that they wanted. Very few apps would actually take an image and the message that came with it.

**Comment by andremarques-gamedev** [comment]
But there isn't still anyway to achieve this now regardless if the apps would accept it or not?

**Comment by olokobayusuf** [comment]
No there isn't (we removed it). We will be adding it back in #49

**Comment by andremarques-gamedev** [comment]
Do you have any prevision date for when the #49 will be available?

**Comment by olokobayusuf** [comment]
Sometime late next week.
