### ISSUE TITLE
Android API 28 version MediaScanning issue

### ISSUE THREAD

**Issue by BaseOfCoding** [olokobayusuf/NatShare-API#52]
When video recording is finished with Natcorder. 
It is stored in the device. 
And when I run the media scanning plugin, it means that the image file is not displayed in the gallery. 
Storage is good. 
There are only problems with media scanning.
And this problem only occurs in Android API version 28 or later. 
I want to know if you are working well. Will it appear right in the gallery after I save it? 
It seems that the problem is not updating the thumbnail.

**Comment by olokobayusuf** [comment]
This doesn't sound like it has anything to do with NatCorder. You have to use the `SaveToCameraRoll` method to copy the video to the gallery.
