### ISSUE TITLE
Slow function : NatShare.Share(image);

### ISSUE THREAD

**Issue by buhnad** [olokobayusuf/NatShare-API#53]
Texture2D image = ...;
NatShare.Share(image);
the above function takes too long to open the share menu specially on android

**Comment by buhnad** [comment]
is it possible to share an image from a path instead of sharing it as a texture, because the share video function is working fast when I share a video captured by NatCorder and nat mic

**Comment by olokobayusuf** [comment]
This is because NatShare must call `Texture2D.EncodeToPNG` function which takes time. We can really only share the PNG- or JPEG-encoded data. So there is no way to avoid this.
