### ISSUE TITLE
Sharing a Texture2D on Android always uses the same thumbnail

### ISSUE THREAD

**Issue by cbauch** [olokobayusuf/NatShare-API#55]
It seems like sharing a texture uses the same filename every time.  The thumbnail used for a shared image in a text message always uses the same thumbnail from the first share.  Either adding an optional file name to the interface or generating unique filenames (such as appending a timestamp) every time a texture is shared would solve this issue.  Currently, a workaround requires saving the texture as a file (which requires additional app permissions) then sharing it from there.

**Comment by olokobayusuf** [comment]
Fixed by #49
