### ISSUE TITLE
Share crash on iOS 12/13

### ISSUE THREAD

**Issue by skibitsky** [olokobayusuf/NatShare-API#57]
An empty scene with one button that executes:
```csharp
var texture = ScreenCapture.CaptureScreenshotAsTexture(2);
NatShare.Share(texture);
```
It works on Android, but crashes on iOS. Tested on iOS 12 Simulator and iOS13 Public Beta 2 device. Logs are attached.

[NativeShare Device iOS13.txt](https://github.com/olokobayusuf/NatShare-API/files/3382126/NativeShare.Device.iOS13.txt)
[NativeShare Simulator iOS12.txt](https://github.com/olokobayusuf/NatShare-API/files/3382127/NativeShare.Simulator.iOS.12.txt)

We used the latest NatShare 1.2 version from GitHub.
Unity version: 2019.1.7f1

Thank you.

**Comment by smxthereisonlyone** [comment]
I have the same issue, how can we fix it?

**Comment by olokobayusuf** [comment]
And can you confirm that you are not calling `Share` from a background thread?

**Comment by skibitsky** [comment]
@olokobayusuf Yes, definitely called from thread 0. See the test project attached below. Crashes in the simulator.

<img width="871" alt="Screenshot 2019-07-26 at 14 29 11" src="https://user-images.githubusercontent.com/15127974/61957791-b8303d80-afc8-11e9-97c4-93d44d496885.png">

[Crash.txt](https://github.com/olokobayusuf/NatShare-API/files/3436104/Crash.txt)
[NatShareTest.zip](https://github.com/olokobayusuf/NatShare-API/files/3436105/NatShareTest.zip)

**Comment by olokobayusuf** [comment]
Okay I'm gonna try to reproduce.

**Comment by olokobayusuf** [comment]
Can you try the code in #49 ? Works for me on iOS 12.

**Comment by olokobayusuf** [comment]
Yup #49 definitely fixes this. The cause of the crash was probably because of the `requestAuthorization` block, which likely invoked the block on a separate thread (hence causing the main thread crash).

**Comment by skibitsky** [comment]
I confirm that it works on iOS 13 device. Thank you!

**Comment by Ruslan-molodec** [comment]
I have the same problem, but I can’t understand how to use code #49

**Comment by olokobayusuf** [comment]
> I have the same problem, but I can’t understand how to use code #49

Have you looked at the [README](https://github.com/natsuite/NatShare-API/tree/payload-api/Assets/NatShare)?

**Comment by Ruslan-molodec** [comment]
Yes, I figured it out! Thanks!😉

пт, 13 дек. 2019 г. в 19:44, Yusuf Olokoba <notifications@github.com>:
