### ISSUE TITLE
Crash just after sharing on iOS

### ISSUE THREAD

**Issue by spatulainteractive** [olokobayusuf/NatShare-API#61]
Unity application appears to stall right after I share a video. The video is successfully getting shared (tried camera roll, email, etc), but it crashes when returning.

Debugging in xcode doesn't give much info:
```
app startup...
2019-10-06 22:01:21.507467-0400 astrogolf[336:9959] UnityIAP: Add transaction observer
2019-10-06 22:01:21.507536-0400 astrogolf[336:9959] UnityIAP UnityEarlyTransactionObserver: Request to initiate queued payments
2019-10-06 22:01:39.300781-0400 astrogolf[336:9959] NatCorder: Prepared MP4 video encoder at resolution 1280x720@30.000000Hz with average bitrate 5909760 and keyframe interval 3s
2019-10-06 22:01:49.466819-0400 astrogolf[336:9959] NatCorder: MP4 recorder finishing
2019-10-06 22:02:27.989389-0400 astrogolf[336:10173] [ShareSheet] connection invalidated
libc++abi.dylib: terminating with uncaught exception of type Il2CppExceptionWrapper
```

I'm using the `payload-api` branch, commit 13fe819. The code to call NatShare is:
```
using (var payload = new SharePayload()) {
    payload.AddMedia("video.mp4");
}
```
I'm on a 10.5 inch iPad pro running ios 13.1.2

**Comment by spatulainteractive** [comment]
Here are some xcode screenshots, in case that is useful. It's not giving a lot of detail..

![Screenshot 2019-10-06 at 22 19 34](https://user-images.githubusercontent.com/56240634/66281051-80c2f480-e887-11e9-9a49-7949ba5e624e.png)
![Screenshot 2019-10-06 at 22 19 50](https://user-images.githubusercontent.com/56240634/66281053-815b8b00-e887-11e9-94b3-0577e71ab3bc.png)
![Screenshot 2019-10-06 at 22 20 05](https://user-images.githubusercontent.com/56240634/66281054-815b8b00-e887-11e9-98e4-7d241dbd3c0e.png)

**Comment by olokobayusuf** [comment]
An `Il2CppExceptionWrapper` indicates an exception being thrown from .NET. So chances are that the crash might be coming from something other than NatShare.

**Comment by kcajf** [comment]
OK, thanks. This definitely only seems to happen when I'm using NatShare though. Perhaps it is the same issue that kkiruk is reporting on the forum? It sounds similar: a crash immediately after pressing save on the share popup.

**Comment by spatulainteractive** [comment]
OK, thanks. This definitely only seems to happen when I'm using NatShare
though. Perhaps it is the same issue that kkiruk is reporting on the forum?
It sounds similar: a crash immediately after pressing save on the share
popup.

**Comment by spatulainteractive** [comment]
OK, thanks. This definitely only seems to happen when I'm using NatShare
though. Perhaps it is the same issue that kkiruk is reporting on the forum?
It sounds similar: a crash immediately after pressing save on the share
popup.

**Comment by spatulainteractive** [comment]
I think the bug has to do with the SharePayload completion handler. I had previously left it unset (null), but setting it to an empty method makes this crash stop happening.

**Comment by olokobayusuf** [comment]
You're right. I've pushed a commit that fixes it.
