### ISSUE TITLE
Saved images are in a folder called "NatShare"

### ISSUE THREAD

**Issue by miketalbott** [olokobayusuf/NatShare-API#8]
On Android, can we replace the "NatShare" from the save path with something generic like "Screenshots" or "Game Photos". Additionally, having the option to provide a directory name would be nice so we could put screenshots in a folder with the Name of the App.  I'd do it myself but I'm a noob at Native Android and don't know how to compile the .java into an .aar file.

**Comment by olokobayusuf** [comment]
Images are only saved in this directory temporarily before being shared or saved to the camera roll. They are not supposed to be viewable in the device gallery. See 9c5f532e03beee85b9a13eab24011801b2be1922
